title: Shirui (Oli) Zhou # your name (or website title) here
logo: "/images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist Intern@ <a href="https://www.worldbank.org/en/businessready">World Bank</a> |
  Data Analyst Intern @ <a href="https://www.ashoka.org/en-us">Ashoka</a> | 
  Operation Assistant @ <a href="https://matters-lab.io/">Matters</a> | 
  Research Assistant @ <a href="https://www.intellisia.org/#/index">Intellisia</a> | 
  Data Science for Public Policy @ Georgetown <a href="https://mccourt.georgetown.edu/master-of-science-in-data-science-for-public-policy/ms-dspp-curriculum/">Georgetown</a>
  
  <br><br>
  A human really love sea ğŸ Skateboarding ğŸ›¹ Guitar ğŸ¸ and photography ğŸ“¹
  <br><br>
  <a href="https://oliz0808eth.substack.com/">Random Thougths in English</a> 
  <br><br>
  <a href="https://matters.town/@olizzz_mushroom">Random Thoughts in Mandarin</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/shirui-zhou-9a2a0719a/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://medium.com/@sz614">Data Science Blog</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
